defmodule Six.TrackIgnoresTest do
  use ExUnit.Case

  import ExUnit.CaptureIO

  alias Six.TrackIgnores

  defp file_stats(path, source) do
    %{
      path: path,
      source: source,
      coverage: List.duplicate(1, length(String.split(source, "\n"))),
      lines: 0,
      relevant: 0,
      covered: 0,
      missed: 0,
      percentage: 100.0
    }
  end

  defp summary(files), do: %{files: files}

  defp config(skip_files \\ []) do
    %Six.Config{skip_files: skip_files}
  end

  describe "render/2" do
    test "produces just the header when there are no ignores" do
      output = TrackIgnores.render(summary([]), config())

      assert output =~ "# Generated by Six"
      assert output =~ "# Commit this file"
      # No actual entries
      lines = String.split(output, "\n", trim: true)
      assert Enum.all?(lines, &String.starts_with?(&1, "#"))
    end

    test "renders @six :ignore functions as `path function_name`" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar do
          :ok
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      assert output =~ "lib/foo.ex bar"
      refute output =~ ":"
    end

    test "renders skip_files patterns at the top, alpha-sorted" do
      patterns = [~r/zebra/, ~r/apple/, "banana"]
      output = TrackIgnores.render(summary([]), config(patterns))

      lines =
        output |> String.split("\n", trim: true) |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == ["banana", "~r/apple/", "~r/zebra/"]
    end

    test "renders comment directive ignores with content hash" do
      source = """
      defmodule Foo do
        def bar do
          # six:ignore:next
          IO.puts("hello")
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      # Should include the path, the enclosing function, and an 8-char hash
      assert output =~ ~r|lib/foo\.ex bar [0-9a-f]{8}|
    end

    test "renders block ignores with content hash and enclosing function" do
      source = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      assert output =~ ~r|lib/foo\.ex bar [0-9a-f]{8}|
    end

    test "renders comment directive without enclosing function as `path hash`" do
      source = """
      # six:ignore:next
      @something :module_level
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      # No function name, just path + hash
      assert output =~ ~r|^lib/foo\.ex [0-9a-f]{8}$|m
    end

    test "is deterministic — same input produces byte-identical output" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar, do: :ok
      end
      """

      summary = summary([file_stats("lib/foo.ex", source)])
      cfg = config([~r/generated/])

      assert TrackIgnores.render(summary, cfg) == TrackIgnores.render(summary, cfg)
    end

    test "sorts code entries alphabetically by formatted line" do
      source_a = """
      defmodule A do
        @six :ignore
        def zebra, do: :ok
        @six :ignore
        def apple, do: :ok
      end
      """

      source_b = """
      defmodule B do
        @six :ignore
        def banana, do: :ok
      end
      """

      output =
        TrackIgnores.render(
          summary([
            file_stats("lib/a.ex", source_a),
            file_stats("lib/b.ex", source_b)
          ]),
          config()
        )

      lines =
        output
        |> String.split("\n", trim: true)
        |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == [
               "lib/a.ex apple",
               "lib/a.ex zebra",
               "lib/b.ex banana"
             ]
    end

    test "hash is stable across line shifts when content does not change" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      shifted = """
      defmodule Foo do
        # extra comment
        # another extra
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      out1 = TrackIgnores.render(summary([file_stats("lib/foo.ex", original)]), config())
      out2 = TrackIgnores.render(summary([file_stats("lib/foo.ex", shifted)]), config())

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, out1)
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, out2)

      assert hash1 == hash2
    end

    test "hash changes when ignored content changes" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          # six:ignore:stop
        end
      end
      """

      modified = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 999
          # six:ignore:stop
        end
      end
      """

      out1 = TrackIgnores.render(summary([file_stats("lib/foo.ex", original)]), config())
      out2 = TrackIgnores.render(summary([file_stats("lib/foo.ex", modified)]), config())

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, out1)
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, out2)

      refute hash1 == hash2
    end

    test "deduplicates @six :ignore entries from multi-clause functions" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar(:a), do: :ok
        @six :ignore
        def bar(:b), do: :ok
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      lines =
        output
        |> String.split("\n", trim: true)
        |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == ["lib/foo.ex bar"]
    end
  end

  describe "write/2" do
    @tag :tmp_dir
    test "writes the .sixignore file at the project root", %{tmp_dir: tmp_dir} do
      original_cwd = File.cwd!()
      File.cd!(tmp_dir)

      on_exit(fn -> File.cd!(original_cwd) end)

      source = """
      defmodule Foo do
        @six :ignore
        def bar, do: :ok
      end
      """

      capture_io(fn ->
        assert :ok =
                 TrackIgnores.write(
                   summary([file_stats("lib/foo.ex", source)]),
                   config()
                 )
      end)

      assert File.exists?(Path.join(tmp_dir, ".sixignore"))
      content = File.read!(Path.join(tmp_dir, ".sixignore"))
      assert content =~ "lib/foo.ex bar"
    end
  end
end
