defmodule Six.TrackIgnoresTest do
  use ExUnit.Case

  import ExUnit.CaptureIO

  alias Six.TrackIgnores

  defp file_stats(path, source) do
    %{
      path: path,
      source: source,
      coverage: List.duplicate(1, length(String.split(source, "\n"))),
      lines: 0,
      relevant: 0,
      covered: 0,
      missed: 0,
      percentage: 100.0
    }
  end

  defp summary(files), do: %{files: files}

  defp config(skip_files \\ []) do
    %Six.Config{skip_files: skip_files}
  end

  describe "render/2" do
    test "produces just the header when there are no ignores" do
      output = TrackIgnores.render(summary([]), config())

      assert output =~ "# Generated by Six"
      assert output =~ "# Commit this file"
      # No actual entries
      lines = String.split(output, "\n", trim: true)
      assert Enum.all?(lines, &String.starts_with?(&1, "#"))
    end

    test "renders @six :ignore functions as `path function_name`" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar do
          :ok
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      assert output =~ "lib/foo.ex bar"
      refute output =~ ":"
    end

    test "renders skip_files patterns at the top, alpha-sorted" do
      patterns = [~r/zebra/, ~r/apple/, "banana"]
      output = TrackIgnores.render(summary([]), config(patterns))

      lines =
        output |> String.split("\n", trim: true) |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == ["banana", "~r/apple/", "~r/zebra/"]
    end

    test "renders comment directive ignores with content hash" do
      source = """
      defmodule Foo do
        def bar do
          # six:ignore:next
          IO.puts("hello")
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      # Should include the path, the enclosing function, and an 8-char hash
      assert output =~ ~r|lib/foo\.ex bar [0-9a-f]{8}|
    end

    test "renders block ignores with content hash and enclosing function" do
      source = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      assert output =~ ~r|lib/foo\.ex bar [0-9a-f]{8}|
    end

    test "renders comment directive without enclosing function as `path hash`" do
      source = """
      # six:ignore:next
      @something :module_level
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      # No function name, just path + hash
      assert output =~ ~r|^lib/foo\.ex [0-9a-f]{8}$|m
    end

    test "is deterministic — same input produces byte-identical output" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar, do: :ok
      end
      """

      summary = summary([file_stats("lib/foo.ex", source)])
      cfg = config([~r/generated/])

      assert TrackIgnores.render(summary, cfg) == TrackIgnores.render(summary, cfg)
    end

    test "sorts code entries alphabetically by formatted line" do
      source_a = """
      defmodule A do
        @six :ignore
        def zebra, do: :ok
        @six :ignore
        def apple, do: :ok
      end
      """

      source_b = """
      defmodule B do
        @six :ignore
        def banana, do: :ok
      end
      """

      output =
        TrackIgnores.render(
          summary([
            file_stats("lib/a.ex", source_a),
            file_stats("lib/b.ex", source_b)
          ]),
          config()
        )

      lines =
        output
        |> String.split("\n", trim: true)
        |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == [
               "lib/a.ex apple",
               "lib/a.ex zebra",
               "lib/b.ex banana"
             ]
    end

    test "hash is stable across line shifts when content does not change" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      shifted = """
      defmodule Foo do
        # extra comment
        # another extra
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      out1 = TrackIgnores.render(summary([file_stats("lib/foo.ex", original)]), config())
      out2 = TrackIgnores.render(summary([file_stats("lib/foo.ex", shifted)]), config())

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, out1)
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, out2)

      assert hash1 == hash2
    end

    test "hash changes when ignored content changes" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          # six:ignore:stop
        end
      end
      """

      modified = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 999
          # six:ignore:stop
        end
      end
      """

      out1 = TrackIgnores.render(summary([file_stats("lib/foo.ex", original)]), config())
      out2 = TrackIgnores.render(summary([file_stats("lib/foo.ex", modified)]), config())

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, out1)
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, out2)

      refute hash1 == hash2
    end

    test "deduplicates @six :ignore entries from multi-clause functions" do
      source = """
      defmodule Foo do
        @six :ignore
        def bar(:a), do: :ok
        @six :ignore
        def bar(:b), do: :ok
      end
      """

      output = TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())

      lines =
        output
        |> String.split("\n", trim: true)
        |> Enum.reject(&String.starts_with?(&1, "#"))

      assert lines == ["lib/foo.ex bar"]
    end
  end

  describe "stability under refactoring" do
    defp render_source(source) do
      TrackIgnores.render(summary([file_stats("lib/foo.ex", source)]), config())
    end

    test "@six :ignore function reorder produces no diff" do
      original = """
      defmodule Foo do
        @six :ignore
        def alpha, do: :ok

        def beta, do: :ok

        @six :ignore
        def gamma, do: :ok
      end
      """

      reordered = """
      defmodule Foo do
        def beta, do: :ok

        @six :ignore
        def gamma, do: :ok

        @six :ignore
        def alpha, do: :ok
      end
      """

      assert render_source(original) == render_source(reordered)
    end

    test "adding a new function above an ignored one does not change the existing entry" do
      before = """
      defmodule Foo do
        @six :ignore
        def existing, do: :ok
      end
      """

      after_ = """
      defmodule Foo do
        def newly_added do
          :hello
        end

        @six :ignore
        def existing, do: :ok
      end
      """

      assert render_source(before) =~ "lib/foo.ex existing"
      assert render_source(after_) =~ "lib/foo.ex existing"
      # Both renders contain the same `existing` line — only difference is no new entries
      before_lines = MapSet.new(String.split(render_source(before), "\n"))
      after_lines = MapSet.new(String.split(render_source(after_), "\n"))
      assert MapSet.subset?(before_lines, after_lines)
    end

    test "renaming an @six :ignore function changes its entry" do
      original = """
      defmodule Foo do
        @six :ignore
        def old_name, do: :ok
      end
      """

      renamed = """
      defmodule Foo do
        @six :ignore
        def new_name, do: :ok
      end
      """

      assert render_source(original) =~ "lib/foo.ex old_name"
      refute render_source(renamed) =~ "lib/foo.ex old_name"
      assert render_source(renamed) =~ "lib/foo.ex new_name"
    end

    test "moving an entire function with a comment directive inside it does not change the hash" do
      original = """
      defmodule Foo do
        def first, do: :ok

        def with_ignore do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
          a + b
        end
      end
      """

      moved = """
      defmodule Foo do
        def with_ignore do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
          a + b
        end

        def first, do: :ok
      end
      """

      assert render_source(original) == render_source(moved)
    end

    test "adding a line inside an ignored block changes the hash" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          # six:ignore:stop
        end
      end
      """

      added = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          # six:ignore:stop
        end
      end
      """

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, render_source(original))
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, render_source(added))

      refute hash1 == hash2
    end

    test "removing a line from an ignored block changes the hash" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          b = 2
          c = 3
          # six:ignore:stop
        end
      end
      """

      shrunk = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          c = 3
          # six:ignore:stop
        end
      end
      """

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, render_source(original))
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, render_source(shrunk))

      refute hash1 == hash2
    end

    test "renaming the enclosing function of a comment directive changes its entry" do
      original = """
      defmodule Foo do
        def old_caller do
          # six:ignore:next
          dangerous_call()
        end
      end
      """

      renamed = """
      defmodule Foo do
        def new_caller do
          # six:ignore:next
          dangerous_call()
        end
      end
      """

      assert render_source(original) =~ ~r|lib/foo\.ex old_caller [0-9a-f]{8}|
      assert render_source(renamed) =~ ~r|lib/foo\.ex new_caller [0-9a-f]{8}|

      # The hash itself should be the same — only the function name changed
      [hash1] = Regex.run(~r/[0-9a-f]{8}/, render_source(original))
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, render_source(renamed))
      assert hash1 == hash2
    end

    test "indentation changes inside an ignored block change the hash" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          # six:ignore:stop
        end
      end
      """

      reindented = """
      defmodule Foo do
        def bar do
            # six:ignore:start
                a = 1
            # six:ignore:stop
        end
      end
      """

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, render_source(original))
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, render_source(reindented))

      # Indentation matters — refactor that touches indentation IS a real change worth flagging
      refute hash1 == hash2
    end

    test "trailing whitespace on ignored lines does not change the hash" do
      original = """
      defmodule Foo do
        def bar do
          # six:ignore:start
          a = 1
          # six:ignore:stop
        end
      end
      """

      with_trailing =
        original
        |> String.replace("a = 1\n", "a = 1   \n")
        |> String.replace("# six:ignore:start\n", "# six:ignore:start  \n")

      [hash1] = Regex.run(~r/[0-9a-f]{8}/, render_source(original))
      [hash2] = Regex.run(~r/[0-9a-f]{8}/, render_source(with_trailing))

      assert hash1 == hash2
    end
  end

  describe "write/2" do
    @tag :tmp_dir
    test "writes the .sixignore file at the project root", %{tmp_dir: tmp_dir} do
      original_cwd = File.cwd!()
      File.cd!(tmp_dir)

      on_exit(fn -> File.cd!(original_cwd) end)

      source = """
      defmodule Foo do
        @six :ignore
        def bar, do: :ok
      end
      """

      capture_io(fn ->
        assert :ok =
                 TrackIgnores.write(
                   summary([file_stats("lib/foo.ex", source)]),
                   config()
                 )
      end)

      assert File.exists?(Path.join(tmp_dir, ".sixignore"))
      content = File.read!(Path.join(tmp_dir, ".sixignore"))
      assert content =~ "lib/foo.ex bar"
    end
  end
end
