name: Setup Elixir
description: Sets up the Elixir environment for the project.
runs:
  using: composite
  steps:
    - name: Elixir
      uses: erlef/setup-beam@v1.24.1
      with:
        version-file: .mise.toml
        version-type: strict
