defmodule Six.TrackIgnores do
  @moduledoc false

  @file_name ".sixignore"
  @hash_length 8

  @header """
  # Generated by Six. Tracks explicit coverage exclusions.
  # Commit this file - changes show up in PR diffs for review.
  """

  @doc """
  Writes the .sixignore file at the project root.
  """
  def write(summary, config) do
    content = render(summary, config)
    path = Path.join(File.cwd!(), @file_name)
    File.write!(path, content)
    IO.puts("Ignore tracking file written to #{@file_name}")
    :ok
  end

  @doc """
  Renders the .sixignore content as a string. Output is deterministic:
  the same set of ignores always produces byte-identical output.
  """
  def render(summary, config) do
    [
      @header,
      render_skip_files(config.skip_files),
      render_code_ignores(summary.files)
    ]
    |> IO.iodata_to_binary()
  end

  defp render_skip_files([]), do: ""

  defp render_skip_files(patterns) do
    patterns
    |> Enum.map(&format_skip_pattern/1)
    |> Enum.sort()
    |> Enum.map(&(&1 <> "\n"))
  end

  defp format_skip_pattern(%Regex{} = regex), do: inspect(regex)
  defp format_skip_pattern(pattern) when is_binary(pattern), do: pattern

  defp render_code_ignores(files) do
    files
    |> Enum.flat_map(&entries_for_file/1)
    |> Enum.uniq()
    |> Enum.sort()
    |> Enum.map(&(&1 <> "\n"))
  end

  defp entries_for_file(%{path: path, source: source}) do
    function_ignore_entries(path, source) ++ comment_ignore_entries(path, source)
  end

  defp function_ignore_entries(path, source) do
    source
    |> Six.Ignore.Functions.ignored_functions()
    |> Enum.map(fn %{function: function} ->
      "#{path} #{display_name(function)}"
    end)
  end

  defp comment_ignore_entries(path, source) do
    case Six.Ignore.ignored_ranges(source) do
      [] ->
        []

      ranges ->
        source_lines = String.split(source, "\n")
        functions = Six.Ignore.Functions.functions(source)

        Enum.map(ranges, fn {start_line, end_line, _type} ->
          hash = content_hash(source_lines, start_line, end_line)

          case enclosing_function_name(functions, start_line) do
            nil -> "#{path} #{hash}"
            name -> "#{path} #{name} #{hash}"
          end
        end)
    end
  end

  @doc false
  def content_hash(source_lines, start_line, end_line) do
    source_lines
    |> Enum.slice((start_line - 1)..(end_line - 1))
    |> Enum.map(&String.trim_trailing/1)
    |> Enum.join("\n")
    |> String.trim()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
    |> String.slice(0, @hash_length)
  end

  defp enclosing_function_name(functions, line_num) do
    functions
    |> Enum.filter(fn %{start_line: s, end_line: e} -> line_num >= s and line_num <= e end)
    |> Enum.max_by(fn %{start_line: s, end_line: e} -> {s, -e} end, fn -> nil end)
    |> case do
      nil -> nil
      %{function: function} -> display_name(function)
    end
  end

  defp display_name(function) do
    function |> String.split(" ", parts: 2) |> List.last()
  end
end
